### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [dpreussler/droidcon_berlin_2017_kotlin_tests#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by dpreussler** [comment]
Hi,

I actually saw the announcement of that and dont get why you should use it. 

Whats the motivation behind it?
The nice thing with kotlin mockito is that its mockito under the hood. 
If you start from scratch you have to solve all the problem Mockito solved over the years. I am not sure this is the right thing to do. But maybe you can convince me ;)

**Comment by oleksiyp** [comment]
You are right, that mockito is dinosaur from Java world that have it all. The question is tiny integtation details with Kotlin. Mockito Kotlin has satisfiable syntax as a Java DSL, but as Kotlin DSL it sucks. 
Check this article: https://dzone.com/articles/new-mocking-tool-for-kotlin-an-alternative-to-java

After all mocking is not a rocket science, all hardcore instrumentation stuff is already in place in MockK, and the question on how to make it better is more on API level

**Comment by dpreussler** [comment]
I agree that mockito is super ugly in Kotlin.
That's why I like kotlin mockito. 
Why not build sth like this, using mockito under the hood?
What you are doing is exactly what Uncle Bob is warning about. Throwing everything overboard for sth new shiny and actually get thrown back years. 
Mocking is not rocket science, I agree, but you will run into issues that people solved years ago in Mockito.
You will miss many small details. People got used to certain behaviors and yours might behave differently.

I appreciate the effort but I would not use sth in larger projects that is not built in top of Mockito.

**Comment by oleksiyp** [comment]
There is limitations in mockito, alike it would never support specifiying
only part of matchers, and more things like that, so it is not
possible/very hard to do it right on top of it.

Overall I think I put a lot of effort and library can compete with Mockito
right now. It even support mocking static methods, that is possible only
with PowerMock. Having one more library is drop in ocean in today Internet.
Not a big deal.

Again Bob Martin is nor saying dont use any new libraries, he says jusy be
careful what you use in PROD. By the way mocking library would never get
there. So it is relatively safe thing to use

So I dont ask you to put right away on 2M LOC project, just try it in your
pet project or alike.

2 янв. 2018 г. 2:44 PM пользователь "Danny Preussler" <
notifications@github.com> написал:

**Comment by dpreussler** [comment]
Bob is actually even against Kotlin  ;)

But I agree, I actually often said to others tests are a good playground for something new.
Might have a look but on first glance the syntax didnt convince. Kotlin mockito together with Kluent made me really happy so far but let's see :)

PS: Adding sth like static mocking would not convince me either as I would see the use of Powermock as a smell in any project that should ring all alarms. Never had the need for it.

**Comment by oleksiyp** [comment]
What can I say? Whole Kotlin idea is about better syntax. So it is in line
with Kotlin ideas.

2 янв. 2018 г. 8:06 PM пользователь "Danny Preussler" <
notifications@github.com> написал:
